### ISSUE TITLE
ทำไมชื่อ id มี - ด้วยละ

### ISSUE THREAD

**Issue by up1** [SCK-SEAL-TEAM-One/shopping-cart#3]
https://github.com/SCK-SEAL-TEAM-One/shopping-cart/blob/aeba33579925a471ec88f2cd81433d0ff9b8d0df/atdd/ui/shopping_cart_success.robot#L80

**Comment by platylm** [comment]
ปรับไปใช้ชื่อ cartProdutName แล้วค่ะ
