### ISSUE TITLE
ทำการ run อย่างไร ไม่มี instruction อธิบายใน readme หรือ wiki

### ISSUE THREAD

**Issue by up1** [SCK-SEAL-TEAM-One/shopping-cart#5]
https://github.com/SCK-SEAL-TEAM-One/shopping-cart/blob/aeba33579925a471ec88f2cd81433d0ff9b8d0df/atdd/api/shopping_cart_success.json#L1

**Comment by platylm** [comment]
เพิ่มใน readme แล้วค่ะ 
https://github.com/SCK-SEAL-TEAM-One/shopping-cart#how-to-run-acceptance-test-api-and-ui
